### ISSUE TITLE
Delete Shadow

### ISSUE THREAD

**Issue by tellfa** [saurabharora90/MaterialArcMenu#3]
hi, how to delete "com.sa90.materialarcmenu.ArcMenu" shadow?
i want dose not show shadow for it?
tnx

**Comment by saurabharora90** [comment]
Hey,

I was working on this today and I have just released a new update to the library. The new version is 1.1.1 (it might take a few minutes to reflect on jCentral).

This version allows you to control the elevation (shadow cast) by the ArcMenu. To control it, you can set the `menu_elevation` to any value you like.

P.S: `menu_elevation` only controls the elevation of the ArcMenu and not of the children. Since you control the children, you should also be able to control their elevation (shadow)

**Comment by tellfa** [comment]
tnx man. you are great <3
